export type PartnerCenterSeedRecord = {
  slug: string;
  region: 'asia-pacific' | 'europe' | 'north-america' | 'latin-america' | 'middle-east-africa' | 'oceania';
  sortOrder: number;
  coverUrl: string;
  logoUrl: string;
  i18n: Record<string, {
    name: string;
    description: string;
    location: string;
    badgeText: string;
    address: string;
    businessHours: string;
    contact: string;
    website: string;
    tags: string[];
  }>;
};

export const PARTNER_CENTER_SEED_RECORDS: PartnerCenterSeedRecord[] = [
  // ── Asia Pacific ──────────────────────────────────────────────────────────
  {
    slug: 'beijing-companion-animal-hospital',
    region: 'asia-pacific',
    sortOrder: 10,
    coverUrl: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=640&h=320&fit=crop',
    logoUrl: 'https://images.unsplash.com/photo-1559305616-3f99cd43e353?w=120&h=120&fit=crop',
    i18n: {
      'zh-CN': {
        name: '北京伴侣动物中心医院',
        description: '国内领先的伴侣动物专科医院，年手术量 5,000+ 台，竑宇 V-CLAMP 核心临床基地。',
        location: '中国 · 北京',
        badgeText: '临床合作',
        address: '北京市朝阳区农展馆南路 1 号',
        businessHours: '周一至周日 08:00–20:00',
        contact: '+86 10-6500-xxxx',
        website: 'https://www.bjpetvet.com',
        tags: ['V-CLAMP', '外科', '培训'],
      },
      en: {
        name: 'Beijing Companion Animal Hospital',
        description: "One of China's leading specialty companion animal hospitals with 5,000+ annual surgeries and a core V-CLAMP clinical base.",
        location: 'China · Beijing',
        badgeText: 'Clinical Partner',
        address: 'No.1 Nongzhan S. Road, Chaoyang, Beijing',
        businessHours: 'Mon–Sun 08:00–20:00',
        contact: '+86 10-6500-xxxx',
        website: 'https://www.bjpetvet.com',
        tags: ['V-CLAMP', 'Surgery', 'Training'],
      },
    },
  },
  {
    slug: 'china-agricultural-university-animal-hospital',
    region: 'asia-pacific',
    sortOrder: 20,
    coverUrl: 'https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=640&h=320&fit=crop',
    logoUrl: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=120&h=120&fit=crop',
    i18n: {
      'zh-CN': {
        name: '中国农业大学动物医院',
        description: '国家重点学科依托单位，承担多项竑宇产品临床试验与学术研究项目。',
        location: '中国 · 北京',
        badgeText: '研究中心',
        address: '北京市海淀区圆明园西路 2 号',
        businessHours: '周一至周五 08:30–17:30',
        contact: '+86 10-6273-xxxx',
        website: 'https://cau.edu.cn',
        tags: ['临床研究', '学术'],
      },
      en: {
        name: 'China Agricultural University Animal Hospital',
        description: 'A national key discipline hub undertaking multiple Hongyu clinical trials and academic research programs.',
        location: 'China · Beijing',
        badgeText: 'Research Center',
        address: '2 Yuanmingyuan W. Road, Haidian, Beijing',
        businessHours: 'Mon–Fri 08:30–17:30',
        contact: '+86 10-6273-xxxx',
        website: 'https://cau.edu.cn',
        tags: ['Clinical Research', 'Academia'],
      },
    },
  },
  {
    slug: 'tokyo-small-animal-medical-center',
    region: 'asia-pacific',
    sortOrder: 30,
    coverUrl: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=640&h=320&fit=crop',
    logoUrl: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=120&h=120&fit=crop',
    i18n: {
      'zh-CN': {
        name: '东京小动物医疗中心',
        description: '日本最大的小动物外科培训中心，竑宇亚太区认证术者培训指定基地。',
        location: '日本 · 东京',
        badgeText: '培训基地',
        address: '東京都港区六本木 3-1-1',
        businessHours: '周一至周六 09:00–18:00',
        contact: '+81 3-xxxx-xxxx',
        website: 'https://www.tosamc.jp',
        tags: ['认证培训', '运动医学'],
      },
      en: {
        name: 'Tokyo Small Animal Medical Center',
        description: "Japan's largest small-animal surgical training facility and Hongyu's designated Asia-Pacific certified surgeon training base.",
        location: 'Japan · Tokyo',
        badgeText: 'Training Base',
        address: '3-1-1 Roppongi, Minato-ku, Tokyo',
        businessHours: 'Mon–Sat 09:00–18:00',
        contact: '+81 3-xxxx-xxxx',
        website: 'https://www.tosamc.jp',
        tags: ['Certified Training', 'Sports Medicine'],
      },
    },
  },
  // ── Europe ────────────────────────────────────────────────────────────────
  {
    slug: 'tierklinik-muenchen',
    region: 'europe',
    sortOrder: 40,
    coverUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=640&h=320&fit=crop',
    logoUrl: 'https://images.unsplash.com/photo-1516841273335-e39b37888115?w=120&h=120&fit=crop',
    i18n: {
      'zh-CN': {
        name: 'Tierklinik München',
        description: '德国顶级动物外科医院，竑宇产品 CE 认证关键临床验证基地，年 V-CLAMP 手术量 800+。',
        location: '德国 · 慕尼黑',
        badgeText: '临床合作',
        address: 'Veterinärstrasse 13, 80539 München',
        businessHours: '周一至周五 08:00–18:00',
        contact: '+49 89-xxxx-xxxx',
        website: 'https://www.tierklinik-muenchen.de',
        tags: ['V-CLAMP', '心血管'],
      },
      en: {
        name: 'Tierklinik München',
        description: "Germany's top animal surgical hospital, key clinical validation base for Hongyu's CE certification with 800+ V-CLAMP procedures annually.",
        location: 'Germany · Munich',
        badgeText: 'Clinical Partner',
        address: 'Veterinärstrasse 13, 80539 München',
        businessHours: 'Mon–Fri 08:00–18:00',
        contact: '+49 89-xxxx-xxxx',
        website: 'https://www.tierklinik-muenchen.de',
        tags: ['V-CLAMP', 'Cardiovascular'],
      },
    },
  },
  {
    slug: 'royal-veterinary-college',
    region: 'europe',
    sortOrder: 50,
    coverUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=640&h=320&fit=crop',
    logoUrl: 'https://images.unsplash.com/photo-1492538368677-f6e0afe31dcc?w=120&h=120&fit=crop',
    i18n: {
      'zh-CN': {
        name: 'Royal Veterinary College',
        description: '欧洲顶尖兽医学院，与竑宇联合开展运动医学产品多中心临床试验。',
        location: '英国 · 伦敦',
        badgeText: '研究中心',
        address: 'Royal College Street, London NW1 0TU',
        businessHours: '周一至周五 09:00–17:00',
        contact: '+44 20-7468-xxxx',
        website: 'https://www.rvc.ac.uk',
        tags: ['临床试验', '学术合作'],
      },
      en: {
        name: 'Royal Veterinary College',
        description: "Europe's top veterinary school, jointly conducting multi-center clinical trials on sports medicine products with Hongyu.",
        location: 'UK · London',
        badgeText: 'Research Center',
        address: 'Royal College Street, London NW1 0TU',
        businessHours: 'Mon–Fri 09:00–17:00',
        contact: '+44 20-7468-xxxx',
        website: 'https://www.rvc.ac.uk',
        tags: ['Clinical Trials', 'Academic Partnership'],
      },
    },
  },
  {
    slug: 'vetagro-sup-lyon',
    region: 'europe',
    sortOrder: 60,
    coverUrl: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=640&h=320&fit=crop',
    logoUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=120&h=120&fit=crop',
    i18n: {
      'zh-CN': {
        name: 'VetAgro Sup',
        description: '法国国立兽医学院，竑宇欧洲区认证术者培训与 ECVIM 学术会议合作机构。',
        location: '法国 · 里昂',
        badgeText: '培训基地',
        address: '1 Avenue Bourgelat, 69280 Marcy-l\'Étoile',
        businessHours: '周一至周五 09:00–17:30',
        contact: '+33 4-xxxx-xxxx',
        website: 'https://www.vetagro-sup.fr',
        tags: ['ECVIM', '认证培训'],
      },
      en: {
        name: 'VetAgro Sup',
        description: "French national veterinary school, Hongyu's European certified surgeon training and ECVIM academic conference partner.",
        location: 'France · Lyon',
        badgeText: 'Training Base',
        address: "1 Avenue Bourgelat, 69280 Marcy-l'Étoile",
        businessHours: 'Mon–Fri 09:00–17:30',
        contact: '+33 4-xxxx-xxxx',
        website: 'https://www.vetagro-sup.fr',
        tags: ['ECVIM', 'Certified Training'],
      },
    },
  },
  // ── North America ─────────────────────────────────────────────────────────
  {
    slug: 'cornell-veterinary-hospital',
    region: 'north-america',
    sortOrder: 70,
    coverUrl: 'https://images.unsplash.com/photo-1607013251379-e6eecfffe234?w=640&h=320&fit=crop',
    logoUrl: 'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=120&h=120&fit=crop',
    i18n: {
      'zh-CN': {
        name: 'Cornell Veterinary Hospital',
        description: '康奈尔大学兽医学院附属医院，竑宇北美 FDA 注册关键临床数据合作机构。',
        location: '美国 · 纽约州',
        badgeText: '临床合作',
        address: '930 Campus Road, Ithaca, NY 14853',
        businessHours: '周一至周五 08:00–17:00',
        contact: '+1 607-253-xxxx',
        website: 'https://www.vet.cornell.edu',
        tags: ['FDA', 'V-CLAMP'],
      },
      en: {
        name: 'Cornell Veterinary Hospital',
        description: 'Affiliated hospital of Cornell College of Veterinary Medicine, key clinical data partner for Hongyu North America FDA registration.',
        location: 'USA · New York',
        badgeText: 'Clinical Partner',
        address: '930 Campus Road, Ithaca, NY 14853',
        businessHours: 'Mon–Fri 08:00–17:00',
        contact: '+1 607-253-xxxx',
        website: 'https://www.vet.cornell.edu',
        tags: ['FDA', 'V-CLAMP'],
      },
    },
  },
  {
    slug: 'uc-davis-veterinary-medical-center',
    region: 'north-america',
    sortOrder: 80,
    coverUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=640&h=320&fit=crop',
    logoUrl: 'https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=120&h=120&fit=crop',
    i18n: {
      'zh-CN': {
        name: 'UC Davis Veterinary Medical Center',
        description: '全美排名前列的兽医学院，与竑宇联合开展心脏起搏器临床前研究。',
        location: '美国 · 加州',
        badgeText: '研究中心',
        address: '1 Shields Ave, Davis, CA 95616',
        businessHours: '周一至周五 08:00–17:00',
        contact: '+1 530-752-xxxx',
        website: 'https://www.vetmed.ucdavis.edu',
        tags: ['心脏起搏器', '临床研究'],
      },
      en: {
        name: 'UC Davis Veterinary Medical Center',
        description: "One of America's top veterinary schools, jointly conducting pre-clinical pacemaker research with Hongyu.",
        location: 'USA · California',
        badgeText: 'Research Center',
        address: '1 Shields Ave, Davis, CA 95616',
        businessHours: 'Mon–Fri 08:00–17:00',
        contact: '+1 530-752-xxxx',
        website: 'https://www.vetmed.ucdavis.edu',
        tags: ['Pacemaker', 'Clinical Research'],
      },
    },
  },
  {
    slug: 'ontario-veterinary-college',
    region: 'north-america',
    sortOrder: 90,
    coverUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=640&h=320&fit=crop',
    logoUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=120&h=120&fit=crop',
    i18n: {
      'zh-CN': {
        name: 'Ontario Veterinary College',
        description: '加拿大最大兽医学院，竑宇北美区认证培训与学术交流核心合作伙伴。',
        location: '加拿大 · 安大略',
        badgeText: '培训基地',
        address: '50 Stone Road E, Guelph, ON N1G 2W1',
        businessHours: '周一至周五 09:00–17:00',
        contact: '+1 519-824-xxxx',
        website: 'https://ovc.uoguelph.ca',
        tags: ['认证培训', '学术'],
      },
      en: {
        name: 'Ontario Veterinary College',
        description: "Canada's largest veterinary school and core partner for Hongyu North America certified training and academic exchange.",
        location: 'Canada · Ontario',
        badgeText: 'Training Base',
        address: '50 Stone Road E, Guelph, ON N1G 2W1',
        businessHours: 'Mon–Fri 09:00–17:00',
        contact: '+1 519-824-xxxx',
        website: 'https://ovc.uoguelph.ca',
        tags: ['Certified Training', 'Academia'],
      },
    },
  },
  // ── Middle East & Africa ──────────────────────────────────────────────────
  {
    slug: 'dubai-veterinary-center',
    region: 'middle-east-africa',
    sortOrder: 100,
    coverUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=640&h=320&fit=crop',
    logoUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=120&h=120&fit=crop',
    i18n: {
      'zh-CN': {
        name: 'Dubai Veterinary Center',
        description: '中东地区领先的动物医疗机构，竑宇产品在海湾地区的首批临床合作伙伴。',
        location: '阿联酋 · 迪拜',
        badgeText: '临床合作',
        address: 'Al Wasl Road, Jumeirah, Dubai, UAE',
        businessHours: '周日至周四 08:00–18:00',
        contact: '+971 4-xxx-xxxx',
        website: 'https://www.dubaivetcenter.ae',
        tags: ['V-CLAMP', '软组织外科'],
      },
      en: {
        name: 'Dubai Veterinary Center',
        description: "A leading veterinary facility in the Middle East and one of the first clinical partners for Hongyu products in the Gulf region.",
        location: 'UAE · Dubai',
        badgeText: 'Clinical Partner',
        address: 'Al Wasl Road, Jumeirah, Dubai, UAE',
        businessHours: 'Sun–Thu 08:00–18:00',
        contact: '+971 4-xxx-xxxx',
        website: 'https://www.dubaivetcenter.ae',
        tags: ['V-CLAMP', 'Soft Tissue Surgery'],
      },
    },
  },
];
