import '@/lib/env';

import { readFile } from 'node:fs/promises';
import path from 'node:path';

import { and, eq, notInArray } from 'drizzle-orm';

import { createSolutionBlockId, type SolutionBlockDraft } from '@/lib/solution-blocks';
import {
  SOLUTION_PRODUCT_SEED_RECORDS,
  type SolutionProductImageSource,
  type SolutionProductSeedRecord,
} from '@/lib/solution-product-seed-data';
import { db } from '@/server/db';
import {
  attachments,
  brands,
  categories,
  productCategories,
  productCoverageBoards,
  products,
  productTranslations,
  solutionBoardLinks,
  solutionContents,
  solutions,
  websiteConfigs,
} from '@/server/db/schema';
import { putStorageObject } from '@/server/oss';
import { getDefaultWebsiteNavColumns } from '@/lib/website-config';

const DEFAULT_LOCALE = 'en';
const LOCAL_IMAGE_DIR = path.resolve(process.cwd(), '../hongyu-web/public/images');
const KEEP_SLUGS = ['v-clamp', 'sports-medicine', 'pacemaker', 'in-research'];

function mimeFromExtension(ext: string) {
  switch (ext.toLowerCase()) {
    case '.webp':
      return 'image/webp';
    case '.png':
      return 'image/png';
    case '.gif':
      return 'image/gif';
    default:
      return 'image/jpeg';
  }
}

async function downloadBuffer(url: string) {
  const response = await fetch(url, {
    headers: {
      'user-agent': 'Mozilla/5.0 (compatible; hongyu-solution-products-seed/1.0)',
    },
  });
  if (!response.ok) {
    throw new Error(`Download failed ${response.status}: ${url}`);
  }
  return Buffer.from(await response.arrayBuffer());
}

async function loadImageBuffer(source: SolutionProductImageSource) {
  if (source.localFile) {
    try {
      const filePath = path.join(LOCAL_IMAGE_DIR, source.localFile);
      const buffer = await readFile(filePath);
      if (buffer.length >= 500) return { buffer, ext: path.extname(source.localFile) || '.jpg' };
    } catch {
      // fall through to remote
    }
  }
  const buffer = await downloadBuffer(source.remoteUrl);
  return { buffer, ext: '.jpg' };
}

async function uploadImage(key: string, source: SolutionProductImageSource) {
  const { buffer, ext } = await loadImageBuffer(source);
  console.log(`上传图片: ${key}`);
  const result = await putStorageObject(key, buffer, mimeFromExtension(ext));
  if (!result.ok) throw new Error(result.error);
  return result.key;
}

/** 生成一份结构完整的最小 PDF（含 xref），用于占位资料下载。 */
function buildMinimalPdf(title: string, bodyLines: string[]): Buffer {
  const escapeText = (value: string) =>
    value
      .replace(/\\/g, '\\\\')
      .replace(/\(/g, '\\(')
      .replace(/\)/g, '\\)')
      // eslint-disable-next-line no-control-regex
      .replace(/[^\u0020-\u007e]/g, '-');

  const contentParts = ['BT', '/F1 18 Tf', '72 760 Td', `(${escapeText(title)}) Tj`, '/F1 11 Tf'];
  for (const line of bodyLines) {
    contentParts.push('0 -26 Td', `(${escapeText(line)}) Tj`);
  }
  contentParts.push('ET');
  const stream = contentParts.join('\n');

  const objectBodies = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
    `<< /Length ${Buffer.byteLength(stream, 'latin1')} >>\nstream\n${stream}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>',
  ];

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];
  objectBodies.forEach((body, index) => {
    offsets.push(Buffer.byteLength(pdf, 'latin1'));
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`;
  });

  const startXref = Buffer.byteLength(pdf, 'latin1');
  pdf += `xref\n0 ${objectBodies.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) {
    pdf += `${offset.toString().padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objectBodies.length + 1} /Root 1 0 R >>\nstartxref\n${startXref}\n%%EOF\n`;

  return Buffer.from(pdf, 'latin1');
}

async function uploadAttachmentPdf(record: SolutionProductSeedRecord, name: string, fileBase: string) {
  const key = `products/${record.slug}/docs/${fileBase}.pdf`;
  const buffer = buildMinimalPdf(name, [
    `Product: ${record.name}`,
    `SPU: ${record.spu}`,
    `Document: ${name}`,
    'Hongyu Medical - veterinary surgical devices',
    'This placeholder document was generated by the seed script.',
  ]);
  console.log(`上传附件: ${key}`);
  const result = await putStorageObject(key, buffer, 'application/pdf');
  if (!result.ok) throw new Error(result.error);
  return { key: result.key, sizeBytes: buffer.length };
}

async function findFirstBrandId() {
  const [row] = await db.select({ id: brands.id }).from(brands).orderBy(brands.createdAt).limit(1);
  return row?.id ?? null;
}

async function findFirstCategoryId() {
  const [row] = await db.select({ id: categories.id }).from(categories).orderBy(categories.sortOrder).limit(1);
  return row?.id ?? null;
}

type UploadedAssets = {
  coverKey: string;
  galleryKeys: string[];
  attachmentFiles: Array<{ name: string; key: string; sizeBytes: number }>;
};

async function uploadAssets(record: SolutionProductSeedRecord): Promise<UploadedAssets> {
  const coverKey = await uploadImage(`products/${record.slug}/cover.jpg`, record.imageSources.cover);

  const galleryKeys: string[] = [];
  for (const [index, source] of record.imageSources.gallery.entries()) {
    galleryKeys.push(await uploadImage(`products/${record.slug}/gallery-${index + 1}.jpg`, source));
  }

  const attachmentFiles: UploadedAssets['attachmentFiles'] = [];
  for (const item of record.attachments) {
    const uploaded = await uploadAttachmentPdf(record, item.name, item.fileBase);
    attachmentFiles.push({ name: item.name, key: uploaded.key, sizeBytes: uploaded.sizeBytes });
  }

  return { coverKey, galleryKeys, attachmentFiles };
}

async function upsertProduct(
  record: SolutionProductSeedRecord,
  assets: UploadedAssets,
  brandId: string | null,
  categoryId: string | null,
) {
  const now = new Date();

  const [existing] = await db
    .select({ id: products.id })
    .from(products)
    .where(eq(products.spu, record.spu))
    .limit(1);

  let productId = existing?.id;

  if (existing) {
    await db
      .update(products)
      .set({
        brandId,
        defaultCategoryId: categoryId,
        status: 'active',
        purchaseMode: 'inquiry',
        boardKey: record.solutionSlug,
        updatedAt: now,
      })
      .where(eq(products.id, existing.id));
  } else {
    const [inserted] = await db
      .insert(products)
      .values({
        spu: record.spu,
        brandId,
        defaultCategoryId: categoryId,
        status: 'active',
        purchaseMode: 'inquiry',
        boardKey: record.solutionSlug,
      })
      .returning({ id: products.id });
    productId = inserted.id;
  }

  if (!productId) throw new Error(`Failed to upsert product ${record.spu}`);

  if (categoryId) {
    await db
      .insert(productCategories)
      .values({ productId, categoryId })
      .onConflictDoNothing();
  }

  const payload = {
    coverUrl: assets.coverKey,
    coverAlt: record.name,
    gallery: assets.galleryKeys.map((url) => ({ url, alt: record.name })),
    tags: [] as string[],
    attachments: assets.attachmentFiles.map((file) => ({
      name: file.name,
      url: file.key,
      mimeType: 'application/pdf',
    })),
    certifications: [] as string[],
  };

  const translationValues = {
    name: record.name,
    slug: record.slug,
    badgeText: record.badgeText,
    extraText: record.extraText,
    shortDescription: record.shortDescription,
    description: record.descriptionHtml,
    seoTitle: record.seoTitle,
    seoDescription: record.seoDescription,
    stats: record.stats,
    payload,
    updatedAt: now,
  };

  const [translation] = await db
    .select({ id: productTranslations.id })
    .from(productTranslations)
    .where(and(eq(productTranslations.productId, productId), eq(productTranslations.locale, DEFAULT_LOCALE)))
    .limit(1);

  if (translation) {
    await db.update(productTranslations).set(translationValues).where(eq(productTranslations.id, translation.id));
  } else {
    await db.insert(productTranslations).values({
      productId,
      locale: DEFAULT_LOCALE,
      ...translationValues,
    });
  }

  await db.delete(attachments).where(eq(attachments.productId, productId));
  if (assets.attachmentFiles.length) {
    await db.insert(attachments).values(
      assets.attachmentFiles.map((file, index) => ({
        productId,
        name: file.name,
        url: file.key,
        mimeType: 'application/pdf',
        sizeBytes: file.sizeBytes,
        sortOrder: index,
      })),
    );
  }

  return productId;
}

function buildRelatedProductsBlock(productIds: string[]): SolutionBlockDraft {
  return {
    id: createSolutionBlockId(),
    type: 'relatedProducts',
    productIds,
    locales: {
      [DEFAULT_LOCALE]: {
        smallTitle: 'PRODUCTS · Product models',
        largeTitle: 'Products in this solution',
        description: 'Explore the devices that make up this solution line.',
        buttonLabel: '',
        badge: '',
        totalHours: '',
        teachingFormat: '',
        trainingCycle: '',
      },
    },
    items: [],
  };
}

async function syncSolutionRelatedProducts(solutionSlug: string, productIds: string[]) {
  const [solution] = await db
    .select({ id: solutions.id })
    .from(solutions)
    .where(eq(solutions.slug, solutionSlug))
    .limit(1);

  if (!solution) {
    console.warn(`跳过关联产品：未找到解决方案 "${solutionSlug}"`);
    return;
  }

  const now = new Date();
  const [content] = await db
    .select({ id: solutionContents.id, blocks: solutionContents.blocks })
    .from(solutionContents)
    .where(eq(solutionContents.solutionId, solution.id))
    .limit(1);

  const existingBlocks = content?.blocks ?? [];
  const preservedBlocks = existingBlocks.filter((block) => block.type !== 'relatedProducts');
  const previousRelated = existingBlocks.find((block) => block.type === 'relatedProducts');

  const relatedBlock: SolutionBlockDraft = previousRelated
    ? { ...previousRelated, productIds }
    : buildRelatedProductsBlock(productIds);

  const blocks = [...preservedBlocks, relatedBlock];

  if (content) {
    await db.update(solutionContents).set({ blocks, updatedAt: now }).where(eq(solutionContents.id, content.id));
  } else {
    await db.insert(solutionContents).values({ solutionId: solution.id, blocks });
  }

  await syncSolutionBoardLink(solution.id, solutionSlug);

  console.log(`已关联 ${productIds.length} 个产品到解决方案: ${solutionSlug}`);
}

async function syncSolutionBoardLink(solutionId: string, solutionSlug: string) {
  const [board] = await db
    .select({ id: productCoverageBoards.id })
    .from(productCoverageBoards)
    .where(eq(productCoverageBoards.boardKey, solutionSlug))
    .limit(1);

  await db.delete(solutionBoardLinks).where(eq(solutionBoardLinks.solutionId, solutionId));

  if (!board) {
    console.warn(`未找到看板 boardKey="${solutionSlug}"，跳过 solution_board_links 同步`);
    return;
  }

  await db.insert(solutionBoardLinks).values({ solutionId, boardId: board.id }).onConflictDoNothing();
}

async function pruneSolutions() {
  const stale = await db
    .select({ id: solutions.id, slug: solutions.slug })
    .from(solutions)
    .where(notInArray(solutions.slug, KEEP_SLUGS));

  if (!stale.length) return;

  await db.delete(solutions).where(notInArray(solutions.slug, KEEP_SLUGS));
  console.log(`已删除多余解决方案: ${stale.map((row) => row.slug).join(', ')}`);
}

async function syncWebsiteNav() {
  const now = new Date();
  const navColumns = getDefaultWebsiteNavColumns();

  const [config] = await db.select({ id: websiteConfigs.id }).from(websiteConfigs).limit(1);

  if (config) {
    await db.update(websiteConfigs).set({ navColumns, updatedAt: now }).where(eq(websiteConfigs.id, config.id));
  } else {
    await db.insert(websiteConfigs).values({ navColumns });
  }

  console.log('已更新站点导航配置。');
}

async function main() {
  const brandId = await findFirstBrandId();
  const categoryId = await findFirstCategoryId();

  if (!brandId) console.warn('未找到品牌，产品 brandId 留空。');
  if (!categoryId) console.warn('未找到分类，产品 defaultCategoryId 留空。');

  const productIdsBySolution = new Map<string, string[]>();

  for (const record of SOLUTION_PRODUCT_SEED_RECORDS) {
    const assets = await uploadAssets(record);
    const productId = await upsertProduct(record, assets, brandId, categoryId);

    const list = productIdsBySolution.get(record.solutionSlug) ?? [];
    list.push(productId);
    productIdsBySolution.set(record.solutionSlug, list);

    console.log(`已写入产品: ${record.spu} (${record.name})`);
  }

  await pruneSolutions();

  for (const [solutionSlug, productIds] of productIdsBySolution) {
    await syncSolutionRelatedProducts(solutionSlug, productIds);
  }

  await syncWebsiteNav();

  console.log(`\n解决方案产品种子数据完成：共 ${SOLUTION_PRODUCT_SEED_RECORDS.length} 个产品。`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
